<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <AssemblyName>Launcher</AssemblyName>
    <RootNamespace>MCCPBuilder.Launcher</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MCCPBuilder.Core\MCCPBuilder.Core.csproj" />
  </ItemGroup>
</Project>
